version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker container
          command: docker build -t navikt/naiserator:canary .
      - run:
          name: Bump version
          command: |
            version=$(./bump.sh)
            git remote set-url origin https://${GITHUB_API_USER}@${GITHUB_API_TOKEN}@github.com/nais/naiserator
            git commit version -m "Version ${version} [skip ci]"
            git tag ${version}
            git push
            git push --tags
