version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Bump version
          command: ./bump.sh
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Build Docker container
          command: docker build -t navikt/naiserator:latest -t navikt/naiserator:$(cat version) .
      - run:
          name: Release new version
          command: |
            version=$(cat version)
            git remote set-url origin https://${GITHUB_API_USER}:${GITHUB_API_TOKEN}@github.com/nais/naiserator
            git commit version -m "Release version ${version} [skip ci]"
            git tag ${version}
            git push
            git push --tags
      - run:
          name: Push Docker container
          command: |
            docker push navikt/naiserator:latest
            docker push navikt/naiserator:$(cat version)
      - run:
          name: Deploy new version to Kubernetes
          command: |
            version=$(cat version)
            naisyaml=$(mktemp -d)
            git clone https://${GITHUB_API_USER}:${GITHUB_API_TOKEN}@github.com/navikt/nais-yaml $naisyaml
            cd $naisyaml
            sed -E -i "s#image: navikt/naiserator:.+#image: navikt/naiserator:${version}#" vars/naiserator.yaml
            git diff
            git commit -a -m "Bump Naiserator to version ${version}"
            git push
