version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Bump version
          command: ./bump.sh
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Build Docker container
          command: docker build -t navikt/naiserator:latest -t navikt/naiserator:$(cat version) .
      - run:
          name: Push latest Docker container
          command: docker push navikt/naiserator:latest navikt/naiserator:$(cat version)
      - run:
          name: Tag version and commit upstream
          command: |
            version=$(cat version)
            git remote set-url origin https://${GITHUB_API_USER}:${GITHUB_API_TOKEN}@github.com/nais/naiserator
            git commit version -m "Release version ${version} [skip ci]"
            git tag ${version}
            git push
            git push --tags
