apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "applications.nais.io"
spec:
  group: "nais.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "applications"
    singular: "application"
    kind: "Application"
    shortNames:
    - app
