---
kind: Namespace
apiVersion: v1
metadata:
  name: nais

---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: naiserator
  name: naiserator
  namespace: nais

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: naiserator
  name: naiserator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: naiserator
  namespace: nais

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: naiserator
  namespace: nais
  labels:
    app: naiserator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naiserator
  template:
    metadata:
      labels:
        app: naiserator
    spec:
      serviceAccountName: naiserator
      containers:
      - name: naiserator
        image: navikt/naiserator:canary
