apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "applications.nais.io"
spec:
  group: "nais.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "applications"
    singular: "application"
    kind: "Application"
    shortNames:
    - app
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - image
            - team
            - port
            - healthcheck
          properties:
            image:
              type: string
            team:
              type: string
            replicas:
              properties:
                min:
                  type: integer
                max:
                  type: integer
                cpuThresholdPercentage:
                  type: integer
            port:
              type: integer
            healthcheck:
              required:
                - liveness
                - readiness
              properties:
                liveness:
                  required:
                    - path
                  properties:
                    path:
                      type: string
                    initialDelay:
                      type: integer
                    timeout:
                      type: integer
                    periodSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                readiness:
                  required:
                    - path
                  properties:
                    path:
                      type: string
                    initialDelay:
                      type: integer
                    timeout:
                      type: integer
            leaderElection:
              type: boolean
            preStopHookPath:
              type: string
            prometheus:
              properties:
                enabled:
                  type: boolean
                path:
                  type: string
            istio:
              properties:
                enabled:
                  type: boolean
            resources:
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                requests:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
            ingress:
              properties:
                disabled:
                  type: boolean
            logformat:
              type: string
            logtransform:
              type: string
            webproxy:
              type: boolean
            secrets:
              type: boolean
            configMaps:
              properties:
                files:
                  type: array
                env:
                  type: array
